inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/webpack*
    - bin/setup
    - bin/yarn
    - config/application.rb
    - config/environments/*.rb
    - config/initializers/*.rb
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*
    - tmp/**/*
    - .git/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/RedundantLineBreak:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20191014150947_add_next_poll_id_to_polls.rb'

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/ClassAndModuleChildren:
  Exclude:
    - test/channels/application_cable/connection_test.rb
    - test/test_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/*_controller.rb'

Style/Documentation:
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - test/**/*.rb
    - db/migrate/*.rb


Layout/LineLength:
  Max: 90

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
